# Generated by Django 2.2.5 on 2019-11-21 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=0)),
                ('send_date', models.DateTimeField()),
                ('phone_from', models.CharField(max_length=20, null=True)),
                ('phone_to', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=300)),
                ('from_name', models.CharField(max_length=50)),
                ('to_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=photos.models.upload_file)),
                ('msg_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_num', models.IntegerField()),
                ('random_url', models.CharField(max_length=15)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Photo_info')),
            ],
        ),
    ]
