version: "3"
services:
  database1:
    image: mysql:5.7
    container_name: database1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
      TZ: "Asia/Seoul"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/testdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    networks:
      - serendipity_net

  serendipity:
    container_name: serendipity
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/home/vscode/app:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
    command: /bin/sh -c "while sleep 1000; do :; done"
    labels:
      serendipity.description: "Django Application"
    networks:
      - serendipity_net

networks:
  serendipity_net: